"""Add is_verified column

Revision ID: 45198f9c5bb5
Revises: cf38ceaef8ba
Create Date: 2025-07-25 16:54:44.842024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45198f9c5bb5'
down_revision = 'cf38ceaef8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
