"""Rename password to password_hash

Revision ID: 7d3ab68e1d66
Revises: b9557766c99a
Create Date: 2025-07-25 07:31:49.629868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d3ab68e1d66'
down_revision = 'b9557766c99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('password'))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index(batch_op.f('password'), ['password'], unique=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
